name: Michael But
favicon: null
layout_spectrum: 0.96537
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6593e0'
    - '#b9d5ed'
    - '#060409'
    - '#4e4f49'
    - '#a19c64'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
